export const CREATE_FEE_REQ = "CREATE_FEE_REQ";
export const CREATE_FEE_SUCCESS = "CREATE_FEE_SUCCESS";
export const CREATE_FEE_FAIL = "CREATE_FEE_FAIL";
export const CREATE_FEE_RESET = "CREATE_FEE_RESET";

export const GET_FEE_REQ = "GET_FEE_REQ";
export const GET_FEE_SUCCESS = "GET_FEE_SUCCESS";
export const GET_FEE_FAIL = "GET_FEE_FAIL";

export const DETAIL_FEE_REQ = "DETAIL_FEE_REQ";
export const DETAIL_FEE_SUCCESS = "DETAIL_FEE_SUCCESS";
export const DETAIL_FEE_FAIL = "DETAIL_FEE_FAIL";

export const UPDATE_FEE_REQ = "UPDATE_FEE_REQ";
export const UPDATE_FEE_SUCCESS = "UPDATE_FEE_SUCCESS";
export const UPDATE_FEE_FAIL = "UPDATE_FEE_FAIL";
export const UPDATE_FEE_RESET = "UPDATE_FEE_RESET";

export const DELETE_FEE_REQ = "DELETE_FEE_REQ";
export const DELETE_FEE_SUCCESS = "DELETE_FEE_SUCCESS";
export const DELETE_FEE_FAIL = "DELETE_FEE_FAIL";
export const DELETE_FEE_RESET = "DELETE_FEE_RESET";

export const DELETE_ALL_FEE_REQ = "DELETE_ALL_FEE_REQ";
export const DELETE_ALL_FEE_SUCCESS = "DELETE_ALL_FEE_SUCCESS";
export const DELETE_ALL_FEE_FAIL = "DELETE_ALL_FEE_FAIL";
export const DELETE_ALL_FEE_RESET = "DELETE_ALL_FEE_RESET";

export const CLEAR_ERROR_DEL_ALL_FEE = "CLEAR_ERROR_DEL_ALL_FEE";
