export const EBOOK_REQ = "EBOOK_REQ";
export const EBOOK_SUCCESS = "EBOOK_SUCCESS";
export const EBOOK_FAIL = "EBOOK_FAIL";
export const EBOOK_RESET = "EBOOK_RESET";

export const GET_EBOOK_REQ = "GET_EBOOK_REQ";
export const GET_EBOOK_SUCCESS = "GET_EBOOK_SUCCESS";
export const GET_EBOOK_FAIL = "GET_EBOOK_FAIL";

export const READ_EBOOK_REQ = "READ_EBOOK_REQ";
export const READ_EBOOK_SUCCESS = "READ_EBOOK_SUCCESS";
export const READ_EBOOK_FAIL = "READ_EBOOK_FAIL";

export const GET_TEACHER_EBOOK_REQ = "GET_TEACHER_EBOOK_REQ";
export const GET_TEACHER_EBOOK_SUCCESS = "GET_TEACHER_EBOOK_SUCCESS";
export const GET_TEACHER_EBOOK_FAIL = "GET_TEACHER_EBOOK_FAIL";

export const EBOOK_DETAIL_REQ = "EBOOK_DETAIL_REQ";
export const EBOOK_DETAIL_SUCCESS = "EBOOK_DETAIL_SUCCESS";
export const EBOOK_DETAIL_FAIL = "EBOOK_DETAIL_FAIL";

export const EBOOK_UPDATE_REQ = "EBOOK_UPDATE_REQ";
export const EBOOK_UPDATE_SUCCESS = "EBOOK_UPDATE_SUCCESS";
export const EBOOK_UPDATE_FAIL = "EBOOK_UPDATE_FAIL";
export const EBOOK_UPDATE_RESET = "EBOOK_UPDATE_RESET";

export const EBOOK_DELETE_REQ = "EBOOK_DELETE_REQ";
export const EBOOK_DELETE_SUCCESS = "EBOOK_DELETE_SUCCESS";
export const EBOOK_DELETE_FAIL = "EBOOK_DELETE_FAIL";
export const EBOOK_DELETE_RESET = "EBOOK_DELETE_RESET";

export const CLEAR_ERROR = "CLEAR_ERROR";
