export const CREATE_EXAM_REQ = "CREATE_EXAM_REQ";
export const CREATE_EXAM_SUCCESS = "CREATE_EXAM_SUCCESS";
export const CREATE_EXAM_FAIL = "CREATE_EXAM_FAIL";
export const CREATE_EXAM_RESET = "CREATE_EXAM_RESET";

export const GET_EXAM_REQ = "GET_EXAM_REQ";
export const GET_EXAM_SUCCESS = "GET_EXAM_SUCCESS";
export const GET_EXAM_FAIL = "GET_EXAM_FAIL";

export const DELETE_ALL_EXAM_REQ = "DELETE_ALL_EXAM_REQ";
export const DELETE_ALL_EXAM_SUCCESS = "DELETE_ALL_EXAM_SUCCESS";
export const DELETE_ALL_EXAM_FAIL = "DELETE_ALL_EXAM_FAIL";
export const DELETE_ALL_EXAM_RESET = "DELETE_ALL_EXAM_RESET";

// GURU
export const TEACHER_EXAM_REQ = "TEACHER_EXAM_REQ";
export const TEACHER_EXAM_SUCCESS = "TEACHER_EXAM_SUCCESS";
export const TEACHER_EXAM_FAIL = "TEACHER_EXAM_FAIL";

export const DETAIL_EXAM_REQ = "DETAIL_EXAM_REQ";
export const DETAIL_EXAM_SUCCESS = "DETAIL_EXAM_SUCCESS";
export const DETAIL_EXAM_FAIL = "DETAIL_EXAM_FAIL";

export const START_EXAM_REQ = "START_EXAM_REQ";
export const START_EXAM_SUCCESS = "START_EXAM_SUCCESS";
export const START_EXAM_FAIL = "START_EXAM_FAIL";

export const UPDATE_EXAM_REQ = "UPDATE_EXAM_REQ";
export const UPDATE_EXAM_SUCCESS = "UPDATE_EXAM_SUCCESS";
export const UPDATE_EXAM_FAIL = "UPDATE_EXAM_FAIL";
export const UPDATE_EXAM_RESET = "UPDATE_EXAM_RESET";

export const DELETE_EXAM_REQ = "DELETE_EXAM_REQ";
export const DELETE_EXAM_SUCCESS = "DELETE_EXAM_SUCCESS";
export const DELETE_EXAM_FAIL = "DELETE_EXAM_FAIL";
export const DELETE_EXAM_RESET = "DELETE_EXAM_RESET";

// SISWA
export const STUDENT_EXAM_REQUEST = "STUDENT_EXAM_REQUEST";
export const STUDENT_EXAM_SUCCESS = "STUDENT_EXAM_SUCCESS";
export const STUDENT_EXAM_FAIL = "STUDENT_EXAM_FAIL";

// LOGGED USER
export const LOGGED_USER_REQ = "LOGGED_USER_REQ";
export const LOGGED_USER_SUCCESS = "LOGGED_USER_SUCCESS";
export const LOGGED_USER_FAIL = "LOGGED_USER_FAIL";
export const LOGGED_USER_RESET = "LOGGED_USER_RESET";

// UNLOCK USER
export const UNLOCK_USER_REQ = "UNLOCK_USER_REQ";
export const UNLOCK_USER_SUCCESS = "UNLOCK_USER_SUCCESS";
export const UNLOCK_USER_FAIL = "UNLOCK_USER_FAIL";
export const UNLOCK_USER_RESET = "UNLOCK_USER_RESET";

// RESET USER
export const RESET_USER_REQ = "RESET_USER_REQ";
export const RESET_USER_SUCCESS = "RESET_USER_SUCCESS";
export const RESET_USER_FAIL = "RESET_USER_FAIL";
export const RESET_USER = "RESET_USER";

export const CLEAR_EXAM_ERROR = "CLEAR_EXAM_ERROR";
