export const WEB_DETAIL_REQ = "WEB_DETAIL_REQ";
export const WEB_DETAIL_SUCCESS = "WEB_DETAIL_SUCCESS";
export const WEB_DETAIL_FAIL = "WEB_DETAIL_FAIL";

export const WEB_UPDATE_REQ = "WEB_UPDATE_REQ";
export const WEB_UPDATE_SUCCESS = "WEB_UPDATE_SUCCESS";
export const WEB_UPDATE_FAIL = "WEB_UPDATE_FAIL";
export const WEB_UPDATE_RESET = "WEB_UPDATE_RESET";
