export const UPLOAD_QUESTION_START = "UPLOAD_QUESTION_START";
export const UPLOAD_QUESTION_SUCCESS = "UPLOAD_QUESTION_SUCCESS";
export const UPLOAD_QUESTION_FAILURE = "UPLOAD_QUESTION_FAILURE";
export const UPLOAD_QUESTION_RESET = "UPLOAD_RESET";

export const DETAIL_QUESTION_START = "DETAIL_QUESTION_START";
export const DETAIL_QUESTION_SUCCESS = "DETAIL_QUESTION_SUCCESS";
export const DETAIL_QUESTION_FAILURE = "DETAIL_QUESTION_FAILURE";

export const UPDATE_QUESTION_REQ = "UPDATE_QUESTION_REQ";
export const UPDATE_QUESTION_SUCCESS = "UPDATE_QUESTION_SUCCESS";
export const UPDATE_QUESTION_FAIL = "UPDATE_QUESTION_FAIL";
export const UPDATE_QUESTION_RESET = "UPDATE_QUESTION_RESET";

export const DELETE_QUESTION_REQ = "DELETE_QUESTION_REQ";
export const DELETE_QUESTION_SUCCESS = "DELETE_QUESTION_SUCCESS";
export const DELETE_QUESTION_FAIL = "DELETE_QUESTION_FAIL";
export const DELETE_QUESTION_RESET = "DELETE_QUESTION_RESET";

export const CLEAR_QUESTION_ERROR = "CLEAR_QUESTION_ERROR";
