export const CREATE_MY_ANSWER_REQ = "CREATE_MY_ANSWER_REQ";
export const CREATE_MY_ANSWER_SUCCESS = "CREATE_MY_ANSWER_SUCCESS";
export const CREATE_MY_ANSWER_FAIL = "CREATE_MY_ANSWER_FAIL";
export const CREATE_MY_ANSWER_RESET = "CREATE_MY_ANSWER_RESET";

export const CREATE_SCORE_ESSAY_REQ = "CREATE_SCORE_ESSAY_REQ";
export const CREATE_SCORE_ESSAY_SUCCESS = "CREATE_SCORE_ESSAY_SUCCESS";
export const CREATE_SCORE_ESSAY_FAIL = "CREATE_SCORE_ESSAY_FAIL";
export const CREATE_SCORE_ESSAY_RESET = "CREATE_SCORE_ESSAY_RESET";

export const GET_MY_ANSWER_REQ = "GET_MY_ANSWER_REQ";
export const GET_MY_ANSWER_SUCCESS = "GET_MY_ANSWER_SUCCESS";
export const GET_MY_ANSWER_FAIL = "GET_MY_ANSWER_FAIL";
export const GET_MY_ANSWER_RESET = "GET_MY_ANSWER_RESET";

export const GET_ALL_ANSWER_REQ = "GET_ALL_ANSWER_REQ";
export const GET_ALL_ANSWER_SUCCESS = "GET_ALL_ANSWER_SUCCESS";
export const GET_ALL_ANSWER_FAIL = "GET_ALL_ANSWER_FAIL";
