export const CREATE_SPP_REQ = "CREATE_SPP_REQ";
export const CREATE_SPP_SUCCESS = "CREATE_SPP_SUCCESS";
export const CREATE_SPP_FAIL = "CREATE_SPP_FAIL";
export const CREATE_SPP_RESET = "CREATE_SPP_RESET";

export const GET_SPP_REQ = "GET_SPP_REQ";
export const GET_SPP_SUCCESS = "GET_SPP_SUCCESS";
export const GET_SPP_FAIL = "GET_SPP_FAIL";

export const GET_SPP_BY_GRADE_REQ = "GET_SPP_BY_GRADE_REQ";
export const GET_SPP_BY_GRADE_SUCCESS = "GET_SPP_BY_GRADE_SUCCESS";
export const GET_SPP_BY_GRADE_FAIL = "GET_SPP_BY_GRADE_FAIL";

export const DELETE_ALL_SPP_REQ = "DELETE_ALL_SPP_REQ";
export const DELETE_ALL_SPP_SUCCESS = "DELETE_ALL_SPP_SUCCESS";
export const DELETE_ALL_SPP_FAIL = "DELETE_ALL_SPP_FAIL";
export const DELETE_ALL_SPP_RESET = "DELETE_ALL_SPP_RESET";

export const DELETE_SPP_REQ = "DELETE_SPP_REQ";
export const DELETE_SPP_SUCCESS = "DELETE_SPP_SUCCESS";
export const DELETE_SPP_FAIL = "DELETE_SPP_FAIL";
export const DELETE_SPP_RESET = "DELETE_SPP_RESET";

export const CLEAR_ERROR = "CLEAR_ERROR";
