export const GRADE_REQ = "GRADE_REQ";
export const GRADE_SUCCESS = "GRADE_SUCCESS";
export const GRADE_FAIL = "GRADE_FAIL";
export const GRADE_RESET = "GRADE_RESET";

export const GET_GRADE_REQ = "GET_GRADE_REQ";
export const GET_GRADE_SUCCESS = "GET_GRADE_SUCCESS";
export const GET_GRADE_FAIL = "GET_GRADE_FAIL";

export const GRADE_DETAIL_REQ = "GRADE_DETAIL_REQ";
export const GRADE_DETAIL_SUCCESS = "GRADE_DETAIL_SUCCESS";
export const GRADE_DETAIL_FAIL = "GRADE_DETAIL_FAIL";

export const STUDENTS_GRADE_REQ = "STUDENTS_GRADE_REQ";
export const STUDENTS_GRADE_SUCCESS = "STUDENTS_GRADE_SUCCESS";
export const STUDENTS_GRADE_FAIL = "STUDENTS_GRADE_FAIL";

export const GRADE_UPDATE_REQ = "GRADE_UPDATE_REQ";
export const GRADE_UPDATE_SUCCESS = "GRADE_UPDATE_SUCCESS";
export const GRADE_UPDATE_FAIL = "GRADE_UPDATE_FAIL";
export const GRADE_UPDATE_RESET = "GRADE_UPDATE_RESET";

export const GRADE_DELETE_REQ = "GRADE_DELETE_REQ";
export const GRADE_DELETE_SUCCESS = "GRADE_DELETE_SUCCESS";
export const GRADE_DELETE_FAIL = "GRADE_DELETE_FAIL";
export const GRADE_DELETE_RESET = "GRADE_DELETE_RESET";

export const GRADE_CLEAR_ERROR = "GRADE_CLEAR_ERROR";
