export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const GET_ALL_USER_REQUEST = "GET_ALL_USER_REQUEST";
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
export const GET_ALL_USER_FAIL = "GET_ALL_USER_FAIL";

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";
export const CREATE_USER_RESET = "CREATE_USER_RESET";

export const DETAIL_USER_REQUEST = "DETAIL_USER_REQUEST";
export const DETAIL_USER_SUCCESS = "DETAIL_USER_SUCCESS";
export const DETAIL_USER_FAIL = "DETAIL_USER_FAIL";
export const DETAIL_USER_RESET = "DETAIL_USER_RESET";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
export const UPDATE_USER_RESET = "UPDATE_USER_RESET";

export const UPDATE_ADMIN_REQUEST = "UPDATE_ADMIN_REQUEST";
export const UPDATE_ADMIN_SUCCESS = "UPDATE_ADMIN_SUCCESS";
export const UPDATE_ADMIN_FAIL = "UPDATE_ADMIN_FAIL";
export const UPDATE_ADMIN_RESET = "UPDATE_ADMIN_RESET";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_USER_RESET = "DELETE_USER_RESET";

export const DELETE_ALL_USER_REQUEST = "DELETE_ALL_USER_REQUEST";
export const DELETE_ALL_USER_SUCCESS = "DELETE_ALL_USER_SUCCESS";
export const DELETE_ALL_USER_FAIL = "DELETE_ALL_USER_FAIL";
export const DELETE_ALL_USER_RESET = "DELETE_ALL_USER_RESET";

export const UPLOAD_START = "UPLOAD_START";
export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS";
export const UPLOAD_FAILURE = "UPLOAD_FAILURE";
export const UPLOAD_RESET = "UPLOAD_RESET";

export const GET_ALL_TEACHER_REQUEST = "GET_ALL_TEACHER_REQUEST";
export const GET_ALL_TEACHER_SUCCESS = "GET_ALL_TEACHER_SUCCESS";
export const GET_ALL_TEACHER_FAIL = "GET_ALL_TEACHER_FAIL";

export const CREATE_TEACHER_REQUEST = "CREATE_TEACHER_REQUEST";
export const CREATE_TEACHER_SUCCESS = "CREATE_TEACHER_SUCCESS";
export const CREATE_TEACHER_FAIL = "CREATE_TEACHER_FAIL";
export const CREATE_TEACHER_RESET = "CREATE_TEACHER_RESET";

export const DETAIL_TEACHER_REQUEST = "DETAIL_TEACHER_REQUEST";
export const DETAIL_TEACHER_SUCCESS = "DETAIL_TEACHER_SUCCESS";
export const DETAIL_TEACHER_FAIL = "DETAIL_TEACHER_FAIL";
export const DETAIL_TEACHER_RESET = "DETAIL_TEACHER_RESET";

export const UPDATE_TEACHER_REQUEST = "UPDATE_TEACHER_REQUEST";
export const UPDATE_TEACHER_SUCCESS = "UPDATE_TEACHER_SUCCESS";
export const UPDATE_TEACHER_FAIL = "UPDATE_TEACHER_FAIL";
export const UPDATE_TEACHER_RESET = "UPDATE_TEACHER_RESET";

export const DELETE_TEACHER_REQUEST = "DELETE_TEACHER_REQUEST";
export const DELETE_TEACHER_SUCCESS = "DELETE_TEACHER_SUCCESS";
export const DELETE_TEACHER_FAIL = "DELETE_TEACHER_FAIL";
export const DELETE_TEACHER_RESET = "DELETE_TEACHER_RESET";

export const DELETE_ALL_TEACHER_REQUEST = "DELETE_ALL_TEACHER_REQUEST";
export const DELETE_ALL_TEACHER_SUCCESS = "DELETE_ALL_TEACHER_SUCCESS";
export const DELETE_ALL_TEACHER_FAIL = "DELETE_ALL_TEACHER_FAIL";
export const DELETE_ALL_TEACHER_RESET = "DELETE_ALL_TEACHER_RESET";

export const UPLOAD_TEACHER_START = "UPLOAD_TEACHER_START";
export const UPLOAD_TEACHER_SUCCESS = "UPLOAD_TEACHER_SUCCESS";
export const UPLOAD_TEACHER_FAILURE = "UPLOAD_TEACHER_FAILURE";
export const UPLOAD_TEACHER_RESET = "UPLOAD_TEACHER_RESET";

export const CLEAR_ERROR = "CLEAR_ERROR";
