export const NEWS_REQ = "NEWS_REQ";
export const NEWS_SUCCESS = "NEWS_SUCCESS";
export const NEWS_FAIL = "NEWS_FAIL";
export const NEWS_RESET = "NEWS_RESET";

export const GET_NEWS_REQ = "GET_NEWS_REQ";
export const GET_NEWS_SUCCESS = "GET_NEWS_SUCCESS";
export const GET_NEWS_FAIL = "GET_NEWS_FAIL";
export const GET_NEWS_RESET = "GET_NEWS_RESET";

export const NEWS_DETAIL_REQ = "NEWS_DETAIL_REQ";
export const NEWS_DETAIL_SUCCESS = "NEWS_DETAIL_SUCCESS";
export const NEWS_DETAIL_FAIL = "NEWS_DETAIL_FAIL";

export const NEWS_UPDATE_REQ = "NEWS_UPDATE_REQ";
export const NEWS_UPDATE_SUCCESS = "NEWS_UPDATE_SUCCESS";
export const NEWS_UPDATE_FAIL = "NEWS_UPDATE_FAIL";
export const NEWS_UPDATE_RESET = "NEWS_UPDATE_RESET";

export const NEWS_DELETE_REQ = "NEWS_DELETE_REQ";
export const NEWS_DELETE_SUCCESS = "NEWS_DELETE_SUCCESS";
export const NEWS_DELETE_FAIL = "NEWS_DELETE_FAIL";
export const NEWS_DELETE_RESET = "NEWS_DELETE_RESET";

export const CLEAR_ERROR = "CLEAR_ERROR";
