export const CLASS_REQ = "CLASS_REQ";
export const CLASS_SUCCESS = "CLASS_SUCCESS";
export const CLASS_FAIL = "CLASS_FAIL";
export const CLASS_RESET = "CLASS_RESET";

export const GET_CLASS_REQ = "GET_CLASS_REQ";
export const GET_CLASS_SUCCESS = "GET_CLASS_SUCCESS";
export const GET_CLASS_FAIL = "GET_CLASS_FAIL";

export const CLASS_DETAIL_REQ = "CLASS_DETAIL_REQ";
export const CLASS_DETAIL_SUCCESS = "CLASS_DETAIL_SUCCESS";
export const CLASS_DETAIL_FAIL = "CLASS_DETAIL_FAIL";

export const STUDENTS_CLASS_REQ = "STUDENTS_CLASS_REQ";
export const STUDENTS_CLASS_SUCCESS = "STUDENTS_CLASS_SUCCESS";
export const STUDENTS_CLASS_FAIL = "STUDENTS_CLASS_FAIL";

export const STUDENTS_GRADE_REQ = "STUDENTS_GRADE_REQ";
export const STUDENTS_GRADE_SUCCESS = "STUDENTS_GRADE_SUCCESS";
export const STUDENTS_GRADE_FAIL = "STUDENTS_GRADE_FAIL";

export const CLASS_UPDATE_REQ = "CLASS_UPDATE_REQ";
export const CLASS_UPDATE_SUCCESS = "CLASS_UPDATE_SUCCESS";
export const CLASS_UPDATE_FAIL = "CLASS_UPDATE_FAIL";
export const CLASS_UPDATE_RESET = "CLASS_UPDATE_RESET";

export const CLASS_DELETE_REQ = "CLASS_DELETE_REQ";
export const CLASS_DELETE_SUCCESS = "CLASS_DELETE_SUCCESS";
export const CLASS_DELETE_FAIL = "CLASS_DELETE_FAIL";
export const CLASS_DELETE_RESET = "CLASS_DELETE_RESET";

export const CLEAR_ERROR = "CLEAR_ERROR";
